import React, { useEffect, useRef, useState } from 'react'
import videojs from 'video.js'
import 'video.js/dist/video-js.css'
import { ipc } from '../services/ipc'
import type { TorrentFileInfo } from '../types'
interface PlayerProps { infoHash: string; file: TorrentFileInfo; onBack: () => void }
const Player: React.FC<PlayerProps> = ({ infoHash, file, onBack }) => { const containerRef = useRef<HTMLDivElement>(null); const playerRef = useRef<ReturnType<typeof videojs> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { let active = true; const init = async () => { try { const streamUrl = await ipc.getStreamUrl(infoHash, file.path); if (!active || !containerRef.current) return; const element = document.createElement('video'); element.className = 'video-js vjs-big-play-centered'; element.setAttribute('playsinline', ''); containerRef.current.replaceChildren(element); const player = videojs(element, { controls: true, autoplay: false, preload: 'auto', fluid: true, responsive: true, sources: [{ src: streamUrl, type: getMime(file.name) }] }); playerRef.current = player; player.on('error', () => { if (active) { setLoading(false); setError('当前格式或编码不受支持，请尝试 MP4 / H.264 文件') } }); if (active) setLoading(false) } catch (reason) { if (active) { setLoading(false); setError(reason instanceof Error ? reason.message : '播放器初始化失败') } } }; void init(); return () => { active = false; playerRef.current?.dispose(); playerRef.current = null } }, [infoHash, file.path, file.name]); return <div className="player-page"><header className="player-header"><button className="back-link" onClick={onBack}>← 返回媒体库</button><div className="player-heading"><span className={`file-icon ${file.type}`}>{file.type === 'audio' ? '♫' : '▶'}</span><div><h2>{file.name}</h2><p>{file.type === 'audio' ? '音频播放' : '视频播放'}</p></div></div></header><div className="player-stage"><div ref={containerRef} className="player-container" />{loading && <div className="player-overlay"><div className="loading-spinner" /><span>正在准备媒体流…</span></div>}{error && <div className="player-overlay player-error"><span>{error}</span><button className="secondary-action" onClick={onBack}>返回媒体库</button></div>}</div></div> }
function getMime(filename: string) { const ext = filename.toLowerCase().slice(filename.lastIndexOf('.')); return ({ '.mp4': 'video/mp4', '.webm': 'video/webm', '.mkv': 'video/x-matroska', '.avi': 'video/x-msvideo', '.mov': 'video/quicktime', '.m4v': 'video/mp4', '.ts': 'video/mp2t', '.mp3': 'audio/mpeg', '.flac': 'audio/flac', '.wav': 'audio/wav', '.aac': 'audio/aac', '.ogg': 'audio/ogg', '.m4a': 'audio/mp4' } as Record<string, string>)[ext] || 'application/octet-stream' }
export default Player
